name: Build Flet Win
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PYTHONUTF8: 1 # <--- ESSA É A CHAVE PARA O SEU ERRO

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v5 
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install flet[all]

      - name: Build Executable
        shell: bash
        run: |
          flet build windows
